### ISSUE TITLE
A free code review

### ISSUE THREAD

**Issue by gezeta-id** [MartinShelley/CodingChallenge#1]
I've heard you don't expect to receive proper feedback from the company that presented the coding challenge to you. This is kind of shitty on their part, but, well, most of them don't give much feedback anyway so... the following is a code review.

### A couple of notes before we start

- All of the following commentary is **never** aimed at you, but at the code. Any shortcomings found do _not_ imply personal criticism or any failure on your part. It's just things you have yet to learn or are currently learning.
- I will be assuming one thing: that the position this challenge was aiming to fill is for a "senior developer". I will not make any more assumptions on the company or the position.
- I won't make a lot of comment about your SCSS. Some, but not a lot. I will **not** run the code itself so I will definitely not point out any potential visual or runtime errors.
- Finally: Do **not** take any of the following as gospel. Some of these things will be more important than others but many can be debated and circumstances may make the counterargument valid. I _will_ try to point out the things that I feel are more important.

### Implications on this being a "senior" position

The assumption made about this being for a "senior" position implies a couple of things. Since different people understand the word "senior" differently, these are some of the things that I will likely include in the review:

- _Not just code_. There are a couple of things I think should be expected from a "senior" developer. So I _will_ talk about your README file, your comments, other additional files -if any-, and your commit history. These are important because they show not just what you did, but _how_ you did it.
- General _structure_ of the code.
- Names of things -variables, functions, objects-
- Tidiness and order. Without too much detail, but at least a general feeling.

#### General presentation - Docs, etc

This _may_ or _may not_ be terribly important in general, but it's something that I think does make a noticeable difference in the context of a hiring challenge. Usually it gives a _better first impression_ which helps you make a much better impact.

The thing is, seeing the repository:

- There is no title or description on the right-side sidebar in Github. This is silly, I know, but it only takes about 10 seconds to write one and gives a much better impression.
- The README is just the original `README.md` from the challenge (with a small addition I'll talk about a bit further below). This, in itself may not be a problem, but as there are no other files explaining what _you_ did, it does leave to be desired. Think that they already have that `README.md` file; _they_ sent it to you. It is _not_ a bad idea to include it in the repository, no. But then again, it's much better if it is not included _as **your** README file_. That is, you need your own README to present what you've done. There are various ways to do this.

So, to give a good impression and present your code I suggest:

You can include the original received file as something like `CHALLENGE-INSTRUCTIONS.md` or `README-ORIGINAL.md` and then add your own `README.md` file. Also, if, _as is the case here_, they give you more than just a text file (i.e. those three images) it is a _good idea_ to put all the files they've sent you in their own folder. You can then name the folder `CHALLENGE-INSTRUCTIONS` and just dump _their_ files there and never need to worry about them again.

In that new `README.md` file you write a good description of what you've built _as if this was a real project_. Include sections explaining things such as a. what the project is, b. how it works, c. instructions to run it. I know _some_ of this may seem like just copying from the original requirements, but still... do it. I do note that you did _some_ of that by **adding** to their README file. The problem with that is that now what you wrote about running the code kind of clashes a bit with _their_ instructions. Who wrote what? What was the original requirement and what is the solution? This is why it's better to use separate files.

Now, _I_ usually include another piece of information. This is optional, but I do think it helps and people tend to appreciate it. This information is "how I think". That is, this will be a **brief** but clear recollection of the decisions and assumptions I've made in the code. Sometimes, if you don't have much to say, you can include this as a section in your `README.md`. Other alternatives are putting if in a more formal `CHANGELOG.md` or in another file with a meaningful name -maybe `ASSUMPTIONS-AND-DECISIONS.md` or something like that-. If the challenge is tightly defined, there won't be many assumptions and you can just keep it in the README file. If it is more _open_ you might benefit from including those decisions in a separate file.

I insist that this file is generally optional, but if you can do it, it does certainly give a nice professional impression. I do notice that you _had_ [some of this in the `README.md` file but you just removed it](https://github.com/MartinShelley/CodingChallenge/commit/a7e5d0ce0d66f17a88e1e5727890c9eb87444d00). Again, if you feel this should not go into the README it's fine, but then do put it _somewhere_.

Next thing, your commit history is somewhat lacking in two fronts, one more important than the other.

The important one is commit messages. Your commit messages are just "creating the banner", "updating quantities on banner & page", "finishing off this", "updating that file", etc. Not all companies will look at your commit history, but those who do will think this is _not so good form_. Make it a habit of writing better commit messages. Refer to typical git usage where you write a single short but descriptive line, then an empty line and then a more detailed explanation of what goes into this commit and why. You don't need to write a book each time, but one or two lines about each included change and its motivation.

One _very nice trick_ to have better commit messages is to to use GIthub's Issues to create tasks, plan your work and relate the commit messages to those tasks. I know this is going a bit overboard and that it adds some work. I don't think you _need_ to do this. But you _can_.

The second thing about your commit history is the history itself. It gives the impression of being _a bit_ erratic. You upload stuff and then you fix them. Or in a single commit you both _move_ a bunch of files and add some code to others. This is less important because they _should_ understand that this is a challenge and done under some stress. But if you can, do try to keep you commit history a bit cleaner. Git can help you with this.

Finally, one last thing about general presentation. You, generally, _shouldn't_ include the `node_modules` directory in the repository. You have included `package.json` and `package-lock.json`. That is enough. In those instructions that you should have included in your `README.md` file you can explain how to run -or whatever- the project and it should start with a "hey, run `npm install` in the project's root". A nice touch to ensure you _don't_ include `node_modules` is creating a `.gitignore` file right when you create the project.

#### On with the code.

Finally, right? (Thanks for your patience)

Let's get the SCSS out of the way. It would probably be better to:

- use some prefix or qualification. You have some generic names like `add-to-basket-banner`, `banner-icon` there which _could_ conflict with names in the original Amazon page. Yeah, maybe they don't _right now_, but you want to ensure you don't break their stuff if they happen to add something and call it `banner-icon`. In the second challenge you introduce [a class which you call simply `offer`](https://github.com/MartinShelley/CodingChallenge/blob/3d182f8863a17ba20a958a2c945b80b82d980d65/Challenge2/css/style.scss#L39) which I _would_ expect to easily conflict with other code. There's even a `display: block` that is [applied to just `button`](https://github.com/MartinShelley/CodingChallenge/blob/3d182f8863a17ba20a958a2c945b80b82d980d65/Challenge1/css/style.scss#L4), every button on the page. I know, not _terrible_ but better not to do that, don't you think?
- There seems to be a _gap_ in your media queries. Between 376 and 415px in the first challenge and 392 and 415px in the second. I'm _not_ saying this is a problem because I haven't run the code, but... is it? It looks like it may be since some paddings are left undefined for that gap but the elements are still shown. Also... why `415px`? A much more common mobile width is `480px`. Ah, you may also want to use `{max,min}-`**`device`**`-width` for mobile.
- Finally, since one of the challenge requirements is a very clear "**mobile only**" you _might_ want to consider a different approach, instead of _always_ applying a bunch of styles and then doing that `display: none` for larger widths, it may be preferable to _only apply the styles on mobile_. That is, put all styles inside a media query that applies only to mobile.

Ok, with that out of the way... **JavaScript**.

I'll look mainly at `/Challenge1/js/script.js` and `/Challenge2/js/script.js` and only very briefly at `server.js`.

About `server.js` I will only say one thing: They asked -for whatever reason- to use port `7000` and you used port `3000`. I know it's silly but I mention it just so you pay a bit more attention to these smaller details ;)

So, the meat: the `script.js` files:

##### General structure

These files are a fairly large block without much thought given to structure or order. I mean, in one everything is thrown inside the load event listener. In the other, half of it is there and the other in a single function. Both seem to be written in a sequential fashion (do this, do that, do that other thing) but without any additional structure. I know the code is not very complicated, but particularly in the first one, it's about 150 continuous lines.

There are also _very few comments_. Having few comments is not, _per se_, a bad thing. But then again the comments that are there aren't really too useful. `//creating the banner and appending it to page` or `// hide/show banner functionality` don't really add much. Meanwhile, you _might_ have added a comment explaining what the behaviour should be when scrolling. Something like "Hide the banner when the original Add to basket button is visible. Show it otherwise". This explains what the code should do so that if there's an error and the code does something different we will know it's wrong.

So back to the general structure thing. How could you make this better? I would suggest doing two things:

1. First you decompose your code into smaller pieces. You break it down into separate parts, each doing its thing. In particular, one thing that will make you stand out is that you separate the initialization into a proper place.
2. Second is that, sure, if you do that, you'll end up throwing a number of names (function and variable names) into the global scope. This is actually _not too bad_ since you're running inside a browser extension but it's still bad form. So then the second thing you do is put the whole thing inside proper encapsulation. Since you're not using any bundler, the easiest thing you could do is encapsulate it all with a so-called [_IIFE_](https://developer.mozilla.org/en-US/docs/Glossary/IIFE).

Doing this, you may end up with something like this:

```javascript
(function() {
    const SOME_CONFIGURATION_VALUE = 200;
    const BANNER_CONTENT = `...`;
    let selectedQuantity = 1;
    // ... 
    function someFunction() {
        // ...
    }
    function someOtherFunction() {
        // ...
    }

    function initializeWidget() {
        const bannerContainer = createBannerContainer();
        assignEventListeners(bannerContainer);
    }

    initializeWidget();
})();
```

_I_, personally, would prefer an explicit `initializeWidget` -or similar name- function. If it is an _extremely simple_ process you might just write...

```javascript
(function() {
    // ... 
    const bannerContainer = createBannerContainer();
    assignEventListeners(bannerContainer);
})();
```

...directly. But, again, the other option is generally preferable.

What using this _IIFE_ achieves is that you make sure that you don't leak any names into the global scope and so avoid potential conflicts with other scripts. You may achieve a similar goal using a bundler or using modules, but this is a very simple solution that suffices for this case and avoids having to introduce extra tools. Since they focus on  _Vanilla JS_, this may be a good thing too.

##### Names

Names, for functions and variables, are quite important. In an interview challenge, using _really good names_ does make you stand out, because many people don't bother. On the other hand, I know thinking up _really good_ names is hard. So, at least aim for _good enough names_.

Your names are not bad, but some of them could be better with very little effort. Some examples: `content` would be much better as a more explicit `BANNER_CONTENT`, also in all caps since it's a hard constant; `banner` refers to the DOM container element so something more explicit like `bannerContainer` or `bannerContainerElement` -or maybe `bannerContainerEl` if you insist- would be better. `selectedQuantity` or `currentQuantity` are a bit better than just `quantity` which means almost nothing.

You will, of course, need more names when you break down the code into different functions as explained above. _Obviously_ don't use `someFunction` but give them proper good names instead :)

##### Other details

It might be a good idea to extract some constants to the top of the script. I'm thinking in particular about the selectors used [here](https://github.com/MartinShelley/CodingChallenge/blob/3d182f8863a17ba20a958a2c945b80b82d980d65/Challenge1/js/script.js#L47-L50). It's interesting to extract your own `"banner-quantity"` selector to a constant in case you change it later, and it is much more interesting to extract original page selectors like `".a-accordion-radio"` to constants because Amazon _can_ change them without previous notice.

I haven't looked into this but: are you _sure_ those selectors are specific enough? Also, that they are always present? I.e. you assume there are two elements in `amazonDealAccordions` but when I view the original page, there aren't any because Amazon does not show deals to everybody. So Then, when you do [this](https://github.com/MartinShelley/CodingChallenge/blob/3d182f8863a17ba20a958a2c945b80b82d980d65/Challenge1/js/script.js#L66-L75), it's going to fail because there aren't always two deal accordions. You should at least enclose that inside a check over `amazonDealAccordions.length`.

Something else I'm not entirely sure of is: Do you actually need a `MutationObserver`? Is it a good idea to do that? The thing is, that, while the _visible_ element on mobile is indeed a bunch of `<span>`s simulating a popup, there is still an actual, native `<select id="mobileQuantityDropDown">` element. And it's value is updated. So, even if you may need to set up a `MutationObserver` it seems a better idea to get the value from the `<select>` element. Anyway, this is not so important, but it might be interesting to think about it.

You use some `==` comparisons to compare what you know is a string `"1"` with a number `1`, [here](https://github.com/MartinShelley/CodingChallenge/blob/3d182f8863a17ba20a958a2c945b80b82d980d65/Challenge1/js/script.js#L99) and a few lines below for `2`. Generally, using `===` is better here since you _know_ you have a string (you just rimmed it), so maybe consider doing

```javascript
if(mutation.target.innerText.trim() === "1") {
```

But even better... [that whole block](https://github.com/MartinShelley/CodingChallenge/blob/3d182f8863a17ba20a958a2c945b80b82d980d65/Challenge1/js/script.js#L99-L110) is kind of repetitively dull. You may want to separate "choosing the values" from "applying the values". What I mean is something _like_ this:

```javascript
        const amountSelected = Number( mutation.target.innerText.trim() );

        bannerQuantity.children[0].selected = amountSelected === 1 ? true: false; 
        bannerQuantity.children[1].selected = amountSelected === 2 ? false : true;
        quantity = amountSelected;
        document.querySelector('#quantity1').value = quantity;
```

Or even better still if you avoid using `.children[0]` and `.children[1]` and just do `bannerQuantity.value = amountSelected;`, as assigning the value to the `<select>` element will choose the appropriate `<option>`. So...

```javascript
        const amountSelected = Number( mutation.target.innerText.trim() );

        bannerQuantity.value = amountSelected;
        quantity = amountSelected;
        document.querySelector('#quantity1').value = quantity;
```

More...

Except for `quantity1` you don't seem to need [any of these ids here](https://github.com/MartinShelley/CodingChallenge/blob/3d182f8863a17ba20a958a2c945b80b82d980d65/Challenge1/js/script.js#L11-L31) and they may conflict with the original ones.

Ah, one question... Why only `1` and `2` as available quantities in your added dropdown? The original dropdown allows me to select up to `4` Echo Dots. Maybe it only shows you `1` and `2`? I don't think it's a fixed value and different customers may get different things. So maybe it would be a good idea to first check how many options Amazon gives you and mimic that. Otherwise if I chose `3`, you original mutation listener wouldn't know what to do.

In the same vein and going back to the correct selectors, [this here](https://github.com/MartinShelley/CodingChallenge/blob/3d182f8863a17ba20a958a2c945b80b82d980d65/Challenge2/js/script.js#L7-L16) seems unnecessarily complicated. Amazon sometimes shows an additional element before results which it devilishly marks as `".s-result-item"` _but_ you may exclude that one by using `".s-result-item[data-uuid]"` which will only select actual results because only those carry a `data-uuid`. Then, you can use `querySelector` (without `All`) to get the first real result.

I'm going to stop here. There may still be a couple of other interesting points but we're getting into very minute detail and particularly specific cases. I don't think we need to go so far for an interview challenge.

### Conclusions

I will insist again in pointing out that this is nothing personal. _Also_, I want to qualify some of the things I've mentioned above.

Some of these things, especially the more general ones, _are more important than others_. I think that for a "senior" position these are the things a company will look for in your code. Others, such as the smaller details on naming or the special cases, while they are nice things to get right, shouldn't usually mean too much. Sure, it's better if you notice them, or some of them, but given the time constrains those things are more easily understandable and forgivable.

As a closing summary, I would say that no, this probably isn't up to was is expected of a senior developer. It's not bad, but it should be better for that position. In particular, the more general, wide-reaching stuff like structure and presentation.

In any case, I hope at least _some_ of all of this helps you a bit for future occasions :)

**Comment by MartinShelley** [comment]
Thank you so much for taking the time to review my code! I haven't had the chance to go through all your comments yet but I really appreciate it! With some of the mistakes you outlined, I can see why now (not using port 7000 for example [facepalm]). 

I will definitely have another go with this challenge at some point with your notes in mind. This is certainly going to help me in the future as I look to move into a developer role. I seriously cannot thank you enough! :)

**Comment by gezeta-id** [comment]
Ah... Feel free to delete this issue when your done with it, or close it or whatever you prefer.
